{% set name = "ctaplot" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctaplot-{{ version }}.tar.gz
  sha256: 8d4671f96e39626e5a494d6e16c6814f6685065bf9b6f6b286c1ef6b375add5f

build:
  entry_points:
    - gammaboard = ctaplot.gammaboard:open_dashboard
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >1.16
    - matplotlib-base >=3.6
    - scipy >=0.19
    - astropy
    - pytables
    - pandas
    - scikit-learn
    - jupyter
    - ipywidgets
    - pyyaml
    - ipympl
    - tqdm

test:
  imports:
    - ctaplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctaplot
  summary: Compute and plot CTA IRFs
  description: |
    low-level reconstruction quality-checks metrics computation and vizualisation 
    for Imaging Atmospheric Cherenkov Telescopes such as CTA
  license: MIT
  license_file: license.rst
  doc_url: https://ctaplot.readthedocs.io/
  dev_url: https://github.com/cta-observatory/ctaplot/

extra:
  recipe-maintainers:
    - vuillaut
